# Generated by Django 4.1 on 2022-09-24 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gifts', '0002_imeino'),
    ]

    operations = [
        migrations.DeleteModel(
            name='IMEINO',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='sold_area',
            new_name='product_name',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='imei',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='phone_model',
        ),
        migrations.RemoveField(
            model_name='gift',
            name='precedence',
        ),
        migrations.RemoveField(
            model_name='offers',
            name='precedence',
        ),
        migrations.AlterField(
            model_name='customer',
            name='shop_name',
            field=models.TextField(default='A to Z'),
        ),
    ]
