# Generated by Django 4.1 on 2022-09-26 02:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gifts', '0003_delete_imeino_rename_sold_area_customer_product_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FixOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=400)),
                ('customer_name', models.CharField(max_length=400)),
                ('sales_no', models.IntegerField()),
                ('gift', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gifts.gift')),
            ],
        ),
    ]
