# Generated by Django 4.1 on 2022-09-26 02:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gifts', '0004_fixoffer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fixoffer',
            old_name='sales_no',
            new_name='quantity',
        ),
    ]
