# Generated by Django 4.1 on 2023-10-02 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gifts', '0005_rename_sales_no_fixoffer_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='offers',
            name='sale_numbers',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='offers',
            name='type_of_offer',
            field=models.CharField(choices=[('After every certain sale', 'After every certain sale'), ('At certain sale position', 'At certain sale position'), ('Weekly Offer', 'Weekly Offer')], max_length=800),
        ),
    ]
